apiVersion: v1
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    labels:
      app: consul
    name: consul
    namespace: vault-deploy
    selfLink: /apis/route.openshift.io/v1/namespaces/vault-deploy/routes/consul
  spec:
    host: consul-vault-deploy.apps.home.lab
    port:
      targetPort: 8500
    to:
      kind: Service
      name: consul
      weight: 100
    wildcardPolicy: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    labels:
      app: vault
    name: vault
    namespace: vault-deploy
    selfLink: /apis/route.openshift.io/v1/namespaces/vault-deploy/routes/vault
  spec:
    host: vault-vault-deploy.apps.home.lab
    port:
      targetPort: 8200
    to:
      kind: Service
      name: vault
      weight: 100
    wildcardPolicy: None
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
